module.exports = {
    TITLE: 'h1.section-hero-header-title',
    SUB_TITLE: 'h2.section-hero-header-subtitle',
    FEEDBACK_COUNT: 'button.widget-pane-link',
    BUTTON_FEEDBACK: '.widget-pane-link', 
    FEEDBACK_LIST: 'section-listbox',
    CURRENT_FEEDBACKS: 'section-review',
    STILL_FEDDBACK_CONTENT: '.section-expand-review',
    FEEDBACK_ACCOUNT_HREF: 'div > a',
    FEEDBACK_ACCOUNT_NAME: 'div.section-review-title > span',
    FEEDBACK_STARS: 'span.section-review-stars',
    FEEDBACK_DATE: 'span.section-review-publish-date',
    FEEDBACK_CONTENT: 'div.section-review-review-content > span.section-review-text',
    FEEDBACK_OWNER_RESPONSE_DATE: 'span.section-review-owner-response-subtitle',
    FEEDBACK_OWNER_RESPONSE_CONTENT: 'div.section-review-text',
}